#!/usr/bin/env -S bash -euo pipefail

action='run'
stamp=0
if [ -f letsencrypt/certificates/hasworn.com.key ]; then
    action='renew'
    stamp=$(stat -c%Y letsencrypt/certificates/hasworn.com.key)
fi

docker run \
    --rm \
    -u $(id -u):$(id -g) \
    -v '/home/hasworn/letsencrypt:/etc/lego_certificates' \
    --env-file environ.production \
    goacme/lego \
        --email norm@hasworn.mnfrancis.com \
        --accept-tos \
        --dns route53 \
        --path /etc/lego_certificates \
            --domains hasworn.com \
            --domains \*.hasworn.com \
                    $action \
                            \
    | tee /tmp/cert.run.$(date +'%Y%m%d%H%M%S') \
    | egrep -v 'Trying renewal|Obtaining bundled|AuthURL|already valid|solver|to solve|Wait for|Checking|validated|Cleaning|no renewal' || true

if [ $(stat -c%Y letsencrypt/certificates/hasworn.com.key) != $stamp ]; then
    echo 'Cert updated, restarting nginx'
    ./compose exec -T nginx /usr/sbin/nginx -s reload
fi
