version: '3.0'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./baked:/baked
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-2c1-f@&vqyh*(eiz4+pyfiuxihuiesg39uz-y=vczx95yrqx%1

  celery:
    environment:
      - SECRET_KEY=django-insecure-2c1-f@&vqyh*(eiz4+pyfiuxihuiesg39uz-y=vczx95yrqx%1
    volumes:
      - .:/app
      - ./baked:/baked

  nginx:
    ports:
      - 8000:8080
    volumes:
      - ./nginx/dev:/etc/nginx/templates
