version: '3.0'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/app
    env_file:
      - environ.dev
    depends_on:
      - db

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8080
    depends_on:
      - app

  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hasworn
      - POSTGRES_PASSWORD=hasworn
      - POSTGRES_DB=hasworn

volumes:
  postgres_data:
