version: '3.0'

services:
  app:
    expose:
      - 8000
    env_file:
      - environ
    depends_on:
      - db

  nginx:
    image: nginx:1.21.1
    depends_on:
      - app
    volumes:
      - baked:/baked
      - ./nginx:/etc/nginx/templates

  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hasworn
      - POSTGRES_PASSWORD=hasworn
      - POSTGRES_DB=hasworn

volumes:
  postgres_data:
  baked:
