version: '3.0'

# Prod config uses journald for logging and the web image corresponding to the current commit

services:
  app:
    image: ghcr.io/norm/hasworn:sha-$COMMIT_SHA
    command: gunicorn hasworn.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - environ.production
    logging:
      driver: journald
