version: '3.0'

services:
  app:
    image: hasworn:latest
    expose:
      - 8000
    env_file:
      - environ
    depends_on:
      - db
    volumes:
      - static:/static

  celery:
    image: hasworn:latest
    env_file:
      - environ
    command: celery --app hasworn worker --concurrency 4 --loglevel info
    depends_on:
      - redis

  celery_beat:
    image: hasworn:latest
    env_file:
      - environ
      - environ.commit
    command: celery --app hasworn beat --schedule /static/beat.db
    volumes:
      - static:/static
    depends_on:
      - celery
      - redis

  nginx:
    image: nginx:1.21.1
    depends_on:
      - app
    volumes:
      - baked:/baked
      - static:/static

  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hasworn
      - POSTGRES_PASSWORD=hasworn
      - POSTGRES_DB=hasworn

  redis:
    image: redis:6.2.5-alpine

volumes:
  postgres_data:
  baked:
  static:
