#!/usr/bin/env -S bash -euo pipefail

declare -a env_vars

[ -n "${DJANGO_SUPERUSER_PASSWORD:-}" ] \
    && env_vars+=(-e DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD)

./compose run \
    "${env_vars[@]}" \
    app python manage.py "$@"
