# Generated by Django 3.2.5 on 2021-07-28 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[('tshirt', 'tshirt')], default='tshirt', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clothing',
                'verbose_name_plural': 'Clothing',
            },
        ),
        migrations.CreateModel(
            name='Worn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.clothing')),
                ('wearer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('wearer', 'clothing')},
            },
        ),
        migrations.AddField(
            model_name='clothing',
            name='worn_by',
            field=models.ManyToManyField(related_name='has_worn', through='clothing.Worn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Wearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('worn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_worn', to='clothing.worn')),
            ],
            options={
                'ordering': ['-day'],
                'unique_together': {('worn', 'day')},
            },
        ),
    ]
