# Generated by Django 3.2.5 on 2021-08-08 06:39

from django.db import migrations, models
import hasworn.clothing.models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hasworn.clothing.models.image_location),
        ),
    ]
