# Generated by Django 3.2.5 on 2021-08-13 09:16

from django.db import migrations, models


def calculate_days_since_last(apps, schema_editor):
    Wearing = apps.get_model('clothing', 'Wearing')
    for wearing in Wearing.objects.all():
        try:
            previous = Wearing.objects.filter(
                    worn = wearing.worn,
                    day__lt = wearing.day,
                ).order_by('-day')[0]
            wearing.days_since_last = (wearing.day - previous.day).days
            wearing.save()
        except IndexError:
            pass


def rewind_days_since_last(apps, schema_editor):
    Wearing = apps.get_model('clothing', 'Wearing')
    for wearing in Wearing.objects.all():
        wearing.days_since_last = None
        wearing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_clothing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearing',
            name='days_since_last',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            calculate_days_since_last,
            rewind_days_since_last,
        ),
    ]
