# Generated by Django 3.2.5 on 2023-02-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_wearing_days_since_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='worn',
            name='no_longer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
