# Generated by Django 3.2.5 on 2021-09-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearer',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
